# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "http://sanjeevkpandit.github.io"
title = "Sanjeev"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 3              # Number of articles displayed on the homepage  # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = "sanjeevkpanditcomnp"      # disqus_shortname
googleAnalytics = "UA-78879488-1"      # UA-XXXXXXXX-X
copyright = ""            # default: author.name ↓        # 默认为下面配置的author.name ↓

# Highlight options.
# See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=false"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[author]                  # essential                     # 必需
  name = "sanjeev"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
# [[menu.main]]
#   name = "Blog"
#   weight = 20
#   identifier = "post"
#   url = "/post/"
# [[menu.main]]
#   name = "Blogs"
#   weight = 600
#   identifier = "posts"
#   url = "/posts/"
#[[menu.main]]
#  name = "Tags"
#  weight = 30
#  identifier = "tags"
#  url = "/tags/"
#[[menu.main]]
#  name = "Categories"
#  weight = 40
#  identifier = "categories"
#  url = "/categories/"
#[[menu.main]]
#  name = "external-link"
#  weight = 50
#  url = "https://gohugo.io"

[permalinks]
  post = "/posts/:slug"

[params]
  since = "2016"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  # mainSections = ["posts"]

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Sanjeev"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Hugo", "theme","jane"]
  description = "Hugo theme jane example site."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  # toc = true                                                                            # 是否开启目录
  # photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  # contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['syntax.css', 'custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # 社交链接
    a-email = "mailto:krsanjeevpandit@gmail.com"
    c-twitter = "https://twitter.com/sanjeevkpandit"
    e-linkedin = "https://np.linked.com/sanjeevkpandit"
    g-github = "https://github.com/sanjeevkpandit"
#    b-stack-overflow = "http://localhost:1313"
#    d-facebook = "http://localhost:1313"
#    f-google = "http://localhost:1313"
#    h-weibo = "http://localhost:1313"
#    i-zhihu = "http://localhost:1313"
#    j-douban = "http://localhost:1313"
#    k-pocket = "http://localhost:1313"
#    l-tumblr = "http://localhost:1313"
#    m-instagram = "http://localhost:1313"
#    n-gitlab = "http://localhost:1313"
#    o-goodreads = "http://localhost:1313"
#    p-coding = "http://localhost:1313"
#    q-bilibili = "http://localhost:1313"
#    r-codeforces = "http://localhost:1313"
#    s-mastodon = "http://localhost:1313"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
